{% set version = "5.2.0" %}

package:
  name: traitlets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traitlets/traitlets-{{ version }}.tar.gz
  sha256: 60474f39bf1d39a11e0233090b99af3acee93bbc2281777e61dd8c87da8a0014

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - traitlets
    - traitlets.config
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://traitlets.readthedocs.org/
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Configuration system for Python applications

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - SylvainCorlay
    - ocefpaf
    - Carreau
    - takluyver
    - rmorshea
    - blink1073
    - zsailer
    - bollwyvl
